### ISSUE TITLE
Running ./config.sh breaks on Kubuntu/Arch: UnboundLocalError: local variable 'cflags_c' referenced before assignment

### ISSUE THREAD

**Issue by selbyk** [trevorlinton/webkit.js#34]
git remote add selby ./config.sh 
Building Ninja files.
Traceback (most recent call last):
  File "./tools/gyp-emscripten/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "./tools/gyp-emscripten/pylib/gyp/__init__.py", line 534, in script_main
    return main(sys.argv[1:])
  File "./tools/gyp-emscripten/pylib/gyp/__init__.py", line 527, in main
    return gyp_main(args)
  File "./tools/gyp-emscripten/pylib/gyp/__init__.py", line 512, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "./tools/gyp-emscripten/pylib/gyp/generator/ninja.py", line 2204, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
UnboundLocalError: local variable 'cflags_c' referenced before assignment
Failed to configure webkit.js properly.

**Comment by selbyk** [comment]
Fixed with https://github.com/selbyk/webkit.js/commit/a1491e043a2df8e36a6ae5c94af223266f60954e

It seems very hacky, but I couldn't find out much about how I should go about setting the var on my system and wasn't sure how to add it to a config file.

What do you think, @trevorlinton?

**Comment by selbyk** [comment]
I'm actually starting to believe this needs to be set to something other than an empty array and that'll solve the other problem too.  Still not sure what it is, though.  Maybe a clone of cflags_cc?

**Comment by JDBStudio** [comment]
Not entirely sure why I am receiving these emails. Any possible
clarification?

**Comment by trevorlinton** [comment]
@JDBStudio your guess is as good as ours...

**Comment by trevorlinton** [comment]
@selbyk All of this entirely is very hacky, most engineering is just that.  A) get it working; B) get it working right, C) get it working the right way. 

Hardly will you ever know what C is without going through A / B.  Go ahead and submit a pull request into the main webkit.js repo, i reconfirmed its building from scratch and pushed a few new commits up this evening, hopefully we can get this rolling soon.

**Comment by JDBStudio** [comment]
Well whatever it is. I do wish you all best of luck tackling it

**Comment by zhrm0110** [comment]
@selbyk 
Hi Selbyk, I have got the same problem with you. Have you solve this problem? Could you please share your solution with me? Think you very much!

**Comment by derofim** [comment]
try to add 
`'cflags_c':'-m32',`

to common.gypi

before each cflags_cc
